[package]
name = "streamer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = "0.26.2"
wows-replays = { path = "../parser" }
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
